from tkinter import *
window = Tk()
window.title('Tkinter Sample Window')
window.geometry('400x500')
greeting = Label(text="Hello User", fg="black", bg='white')
button = Button(text="Click me", bg="black", fg="white")
entry = Entry(fg="yellow", bg="blue", width=50)
greeting.pack()
button.pack()
entry.pack()
frame = Frame(master=window, relief=RAISED, borderwidth=5)
frame.pack()
Label = Label(master=frame, text="Sample Frame")
Label.pack()
textbox = Text(fg="green", bg="yellow")
textbox.pack()
window.mainloop()